on: [push, pull_request]

jobs:
  json-linter:
    runs-on: ubuntu-latest
    - name: Run JSON Lint
      run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)